dataSourceClassName: org.postgresql.ds.PGSimpleDataSource

dataSource:
  user: dev
  password: dev
  databaseName: dev
  portNumber: 5432
  serverName: 127.0.0.1

response:
  timeout: 9000

server:
  port: 8081
